name: Authentication tests

on:
   push:
   
    

jobs:
   test:
     name: Run tests from components/Main folder
     runs-on: ubuntu-latest
     steps: 
       - name: Checkout
         uses: actions/checkout@v3

       - name: Setup node
         uses: actions/setup-node@v3
         with: 
           node-version: 19
           cache: npm
           cache-dependency-path: frontend/package-lock.json
       - name: Install
         run: npm ci
       - name: Test
         run: npm run coverage 
   
