name: "Close stale issues"
on:
  schedule:
  - cron: "*/10 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Check the deployed service URL
      uses: vcnc-hex/url-health-check-action@v2
      with:
        # Check the following URLs one by one sequentially
        url: https://grasp-daas.com/api/cm-dev/health-check/
        # Max time to keep requesting url
        max-time: 1m
        # Max time until a request times out
        request-timeout: 10s
        # Fail this action after this many failed attempts
        # set to "until-max-time" to request forever
        max-attempts: 1 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 1s
    
