name: "Customer managerment endpoints"
on:
  schedule:
  - cron: "*/10 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Check the deployed service URL
      uses: vcnc-hex/url-health-check-action@v2
      with:
        # Check the following URLs one by one sequentially
        url: https://grasp-daas.com/api/cm-dev/v1/health-check/        
        max-time: 1m        
        request-timeout: 10s                
        # Delay between retries
        retry-delay: 1s
    
